//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api", ConfigurationName="ServiceReference2.RoutePlannerServiceImpl")]
    public interface RoutePlannerServiceImpl {
        
        // CODEGEN: Parameter 'preparePlanReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="preparePlanReturn")]
        WebServiceApp.ServiceReference2.preparePlanResponse preparePlan(WebServiceApp.ServiceReference2.preparePlanRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pojo.api")]
    public partial class RoutePoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool hideField;
        
        private int periodidField;
        
        private string point_CoordinatesField;
        
        private string point_NameField;
        
        private double point_OrientationField;
        
        private double point_SpeedField;
        
        private int pointidField;
        
        private int preferred_OrderField;
        
        private int req_idField;
        
        private string timeField;
        
        private string user_MessageField;
        
        private string weekdayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool hide {
            get {
                return this.hideField;
            }
            set {
                this.hideField = value;
                this.RaisePropertyChanged("hide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int periodid {
            get {
                return this.periodidField;
            }
            set {
                this.periodidField = value;
                this.RaisePropertyChanged("periodid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string point_Coordinates {
            get {
                return this.point_CoordinatesField;
            }
            set {
                this.point_CoordinatesField = value;
                this.RaisePropertyChanged("point_Coordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string point_Name {
            get {
                return this.point_NameField;
            }
            set {
                this.point_NameField = value;
                this.RaisePropertyChanged("point_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double point_Orientation {
            get {
                return this.point_OrientationField;
            }
            set {
                this.point_OrientationField = value;
                this.RaisePropertyChanged("point_Orientation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double point_Speed {
            get {
                return this.point_SpeedField;
            }
            set {
                this.point_SpeedField = value;
                this.RaisePropertyChanged("point_Speed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int pointid {
            get {
                return this.pointidField;
            }
            set {
                this.pointidField = value;
                this.RaisePropertyChanged("pointid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int preferred_Order {
            get {
                return this.preferred_OrderField;
            }
            set {
                this.preferred_OrderField = value;
                this.RaisePropertyChanged("preferred_Order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int req_id {
            get {
                return this.req_idField;
            }
            set {
                this.req_idField = value;
                this.RaisePropertyChanged("req_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string user_Message {
            get {
                return this.user_MessageField;
            }
            set {
                this.user_MessageField = value;
                this.RaisePropertyChanged("user_Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string weekday {
            get {
                return this.weekdayField;
            }
            set {
                this.weekdayField = value;
                this.RaisePropertyChanged("weekday");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pojo.api")]
    public partial class PathPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorField;
        
        private string hideField;
        
        private bool originalField;
        
        private string original_POField;
        
        private string periodidField;
        
        private double point_AcclField;
        
        private string point_CoordinatesField;
        
        private string point_NameField;
        
        private string point_OrientationField;
        
        private string point_SpeedField;
        
        private double point_SteeringField;
        
        private string pointidField;
        
        private string preferred_OrderField;
        
        private int req_idField;
        
        private string timeField;
        
        private string user_MessageField;
        
        private string weekdayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string hide {
            get {
                return this.hideField;
            }
            set {
                this.hideField = value;
                this.RaisePropertyChanged("hide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool original {
            get {
                return this.originalField;
            }
            set {
                this.originalField = value;
                this.RaisePropertyChanged("original");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string original_PO {
            get {
                return this.original_POField;
            }
            set {
                this.original_POField = value;
                this.RaisePropertyChanged("original_PO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string periodid {
            get {
                return this.periodidField;
            }
            set {
                this.periodidField = value;
                this.RaisePropertyChanged("periodid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double point_Accl {
            get {
                return this.point_AcclField;
            }
            set {
                this.point_AcclField = value;
                this.RaisePropertyChanged("point_Accl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string point_Coordinates {
            get {
                return this.point_CoordinatesField;
            }
            set {
                this.point_CoordinatesField = value;
                this.RaisePropertyChanged("point_Coordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string point_Name {
            get {
                return this.point_NameField;
            }
            set {
                this.point_NameField = value;
                this.RaisePropertyChanged("point_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string point_Orientation {
            get {
                return this.point_OrientationField;
            }
            set {
                this.point_OrientationField = value;
                this.RaisePropertyChanged("point_Orientation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string point_Speed {
            get {
                return this.point_SpeedField;
            }
            set {
                this.point_SpeedField = value;
                this.RaisePropertyChanged("point_Speed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double point_Steering {
            get {
                return this.point_SteeringField;
            }
            set {
                this.point_SteeringField = value;
                this.RaisePropertyChanged("point_Steering");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string pointid {
            get {
                return this.pointidField;
            }
            set {
                this.pointidField = value;
                this.RaisePropertyChanged("pointid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string preferred_Order {
            get {
                return this.preferred_OrderField;
            }
            set {
                this.preferred_OrderField = value;
                this.RaisePropertyChanged("preferred_Order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int req_id {
            get {
                return this.req_idField;
            }
            set {
                this.req_idField = value;
                this.RaisePropertyChanged("req_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string user_Message {
            get {
                return this.user_MessageField;
            }
            set {
                this.user_MessageField = value;
                this.RaisePropertyChanged("user_Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string weekday {
            get {
                return this.weekdayField;
            }
            set {
                this.weekdayField = value;
                this.RaisePropertyChanged("weekday");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="preparePlan", WrapperNamespace="http://api", IsWrapped=true)]
    public partial class preparePlanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("routePoints")]
        public WebServiceApp.ServiceReference2.RoutePoint[] routePoints;
        
        public preparePlanRequest() {
        }
        
        public preparePlanRequest(WebServiceApp.ServiceReference2.RoutePoint[] routePoints) {
            this.routePoints = routePoints;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="preparePlanResponse", WrapperNamespace="http://api", IsWrapped=true)]
    public partial class preparePlanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("preparePlanReturn")]
        public WebServiceApp.ServiceReference2.PathPoint[] preparePlanReturn;
        
        public preparePlanResponse() {
        }
        
        public preparePlanResponse(WebServiceApp.ServiceReference2.PathPoint[] preparePlanReturn) {
            this.preparePlanReturn = preparePlanReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoutePlannerServiceImplChannel : WebServiceApp.ServiceReference2.RoutePlannerServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutePlannerServiceImplClient : System.ServiceModel.ClientBase<WebServiceApp.ServiceReference2.RoutePlannerServiceImpl>, WebServiceApp.ServiceReference2.RoutePlannerServiceImpl {
        
        public RoutePlannerServiceImplClient() {
        }
        
        public RoutePlannerServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutePlannerServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutePlannerServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutePlannerServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceApp.ServiceReference2.preparePlanResponse WebServiceApp.ServiceReference2.RoutePlannerServiceImpl.preparePlan(WebServiceApp.ServiceReference2.preparePlanRequest request) {
            return base.Channel.preparePlan(request);
        }
        
        public WebServiceApp.ServiceReference2.PathPoint[] preparePlan(WebServiceApp.ServiceReference2.RoutePoint[] routePoints) {
            WebServiceApp.ServiceReference2.preparePlanRequest inValue = new WebServiceApp.ServiceReference2.preparePlanRequest();
            inValue.routePoints = routePoints;
            WebServiceApp.ServiceReference2.preparePlanResponse retVal = ((WebServiceApp.ServiceReference2.RoutePlannerServiceImpl)(this)).preparePlan(inValue);
            return retVal.preparePlanReturn;
        }
    }
}
