//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions_Type
    {
        public Actions_Type()
        {
            this.Object_Periods = new HashSet<Object_Periods>();
        }
    
        public int Action_Type_ID { get; set; }
        public Nullable<int> Action_Type_Order { get; set; }
        public string Action_Type { get; set; }
        public string Action_Type_Text { get; set; }
        public string Action_Type_Image { get; set; }
        public string Action_Type_Name { get; set; }
        public string Action_Type_Icom { get; set; }
        public string Action_Type_Pic { get; set; }
        public string Action_Type_Snd { get; set; }
        public Nullable<decimal> Expected_Duration { get; set; }
        public Nullable<decimal> MaxSpeed { get; set; }
        public Nullable<decimal> MaxDuration { get; set; }
        public string ActionEffect { get; set; }
        public Nullable<int> ActionEffectIndex { get; set; }
    
        public virtual ICollection<Object_Periods> Object_Periods { get; set; }
    }
}
