//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminState
    {
        public int AdminState_ID { get; set; }
        public string AdminState_Name { get; set; }
        public Nullable<int> AdminState_Val { get; set; }
        public string AdminState_Color { get; set; }
    }
}
