//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARConfig
    {
        public int Id { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<int> mode_config { get; set; }
        public Nullable<bool> fast_mode { get; set; }
        public Nullable<bool> xy_mode { get; set; }
        public Nullable<int> orders { get; set; }
        public Nullable<int> vehicles { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> pairs { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public string time_window_min { get; set; }
        public Nullable<int> time_window_max { get; set; }
        public Nullable<int> time_window_width { get; set; }
        public Nullable<int> end_time { get; set; }
        public Nullable<System.DateTime> completetime { get; set; }
        public Nullable<decimal> serviceduration { get; set; }
        public Nullable<bool> fixed_locations { get; set; }
        public Nullable<bool> random_orders { get; set; }
        public Nullable<bool> random_fleet { get; set; }
        public Nullable<bool> random_pickdrop { get; set; }
        public Nullable<bool> random_clusters { get; set; }
        public Nullable<bool> fromtable { get; set; }
        public Nullable<int> penalty_min { get; set; }
        public Nullable<int> penalty_max { get; set; }
        public Nullable<int> demand_min { get; set; }
        public Nullable<int> demand_max { get; set; }
        public Nullable<decimal> prob_rnd_pnt { get; set; }
        public Nullable<decimal> prob_rnd_drop { get; set; }
        public Nullable<bool> success { get; set; }
        public Nullable<int> run_index { get; set; }
        public Nullable<int> runindex_touse { get; set; }
        public string Language { get; set; }
        public Nullable<double> FixedCost { get; set; }
        public Nullable<int> cost_coefficient_max { get; set; }
        public Nullable<double> CostFactor { get; set; }
        public Nullable<double> TimeFactor { get; set; }
        public Nullable<double> ArcCost { get; set; }
        public Nullable<double> DelayCostFactor { get; set; }
        public Nullable<decimal> DistanceUperTimeU { get; set; }
        public Nullable<decimal> LowSpeed { get; set; }
        public Nullable<decimal> TimeDistanceCostRatio { get; set; }
        public Nullable<int> y_max { get; set; }
        public Nullable<int> x_max { get; set; }
        public Nullable<decimal> secPerTick { get; set; }
        public Nullable<int> dcompress { get; set; }
        public Nullable<int> tcompress { get; set; }
        public string hub { get; set; }
        public string vertex1 { get; set; }
        public string vertex2 { get; set; }
        public Nullable<int> cluster_min { get; set; }
        public Nullable<int> cluster_max { get; set; }
        public Nullable<int> cluster_rad { get; set; }
        public string map { get; set; }
        public string map_config { get; set; }
        public Nullable<int> orgn_limit { get; set; }
        public Nullable<int> dstn_limit { get; set; }
        public Nullable<int> distortion { get; set; }
        public Nullable<int> BreakDuration { get; set; }
        public Nullable<int> BreakShiftMins { get; set; }
        public Nullable<int> Break_TW_Mins { get; set; }
        public Nullable<int> SetSize { get; set; }
        public Nullable<int> SetStep { get; set; }
        public Nullable<double> SetFactor { get; set; }
        public Nullable<int> Categories { get; set; }
        public Nullable<int> pp_cluster { get; set; }
        public Nullable<decimal> time_weight { get; set; }
        public Nullable<bool> mandate_different { get; set; }
        public Nullable<bool> mandate_both { get; set; }
        public Nullable<int> served_clusters { get; set; }
        public string vhub { get; set; }
        public Nullable<double> interim_time { get; set; }
        public Nullable<int> treated_tasks { get; set; }
        public Nullable<bool> include_communicated { get; set; }
        public Nullable<int> candidate_vehicles { get; set; }
        public Nullable<bool> virtuals { get; set; }
        public Nullable<decimal> prob_shadow { get; set; }
        public Nullable<bool> Start_AtZero { get; set; }
        public Nullable<double> Min_Start_Time { get; set; }
        public Nullable<double> Max_Range { get; set; }
        public Nullable<double> Min_Stops { get; set; }
        public Nullable<double> Max_Stops { get; set; }
        public string policy { get; set; }
        public Nullable<decimal> prob_rnd_start { get; set; }
        public Nullable<bool> map_shrink { get; set; }
        public Nullable<int> Expedite_Factor { get; set; }
        public Nullable<bool> random_multi { get; set; }
        public Nullable<int> SearchTime { get; set; }
        public Nullable<int> Meta { get; set; }
        public Nullable<bool> Capacity_AtZero { get; set; }
        public string Capacities_AtZero { get; set; }
        public Nullable<double> Min_Value { get; set; }
        public Nullable<double> Max_Value { get; set; }
        public Nullable<bool> append_tasks { get; set; }
        public Nullable<bool> fromdvtable { get; set; }
        public string task_table { get; set; }
        public string dv_table { get; set; }
        public Nullable<int> vehicle_type { get; set; }
        public Nullable<int> PickUnitDuration { get; set; }
        public Nullable<int> DropUnitDuration { get; set; }
        public Nullable<int> PickEntryDuration { get; set; }
        public Nullable<int> PickExitDuration { get; set; }
        public Nullable<int> DropEntryDuration { get; set; }
        public Nullable<int> DropExitDuration { get; set; }
        public Nullable<int> MaxInLineItem { get; set; }
        public Nullable<bool> BinPack { get; set; }
        public Nullable<int> MaxInBin { get; set; }
        public Nullable<int> UtcAddMins { get; set; }
        public Nullable<double> Max_Time { get; set; }
        public Nullable<double> Max_Cycle { get; set; }
        public Nullable<bool> ProcessFacilities { get; set; }
        public Nullable<bool> AllVehicles { get; set; }
        public Nullable<bool> AllFacilities { get; set; }
        public string map2 { get; set; }
        public string map3 { get; set; }
        public string map4 { get; set; }
        public Nullable<int> map_horizon { get; set; }
        public Nullable<System.DateTime> LastTD { get; set; }
        public Nullable<int> RefreshTime { get; set; }
        public Nullable<int> RefreshInterval { get; set; }
        public Nullable<double> StretchFactor { get; set; }
        public Nullable<int> treated_max { get; set; }
        public Nullable<int> candidate_max { get; set; }
        public Nullable<bool> AdjustDurations { get; set; }
        public string Capacities_BP { get; set; }
        public Nullable<bool> CapConcurrent { get; set; }
        public Nullable<int> ReCycleMode { get; set; }
        public Nullable<int> PercentPerHour { get; set; }
        public Nullable<int> PercentPerDay { get; set; }
        public Nullable<bool> SnapToTOD { get; set; }
        public Nullable<bool> EnableDDD { get; set; }
        public Nullable<bool> AdjustSkills { get; set; }
        public Nullable<int> CapSkills { get; set; }
        public Nullable<bool> EnablePickOnly { get; set; }
        public Nullable<bool> FullLoad { get; set; }
        public string Factories { get; set; }
        public string mapKey { get; set; }
        public string map2Key { get; set; }
        public string map3Key { get; set; }
        public string map4Key { get; set; }
        public Nullable<bool> MultiContainer { get; set; }
        public Nullable<bool> OptimizeDist { get; set; }
        public Nullable<int> Time_Span { get; set; }
        public Nullable<int> Location_Span { get; set; }
    }
}
