//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArryMul
    {
        public int ArryMul_ID { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public string RowEntries { get; set; }
    }
}
