//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box_State
    {
        public int Box_State_ID { get; set; }
        public Nullable<int> Box_ID { get; set; }
        public Nullable<int> Object_ID { get; set; }
        public Nullable<int> Compartment_ID { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public Nullable<int> Status_ID { get; set; }
    }
}
