//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container_Periods
    {
        public int Container_Period_ID { get; set; }
        public Nullable<int> Container_ID { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<int> Box_ID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Schd_Start_Time { get; set; }
        public Nullable<System.DateTime> Schd_End_Time { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<int> Point_Mon { get; set; }
        public Nullable<int> Point_Tue { get; set; }
        public Nullable<int> Point_Wed { get; set; }
        public Nullable<int> Point_Thu { get; set; }
        public Nullable<int> Point_Fri { get; set; }
        public Nullable<int> Point_Sat { get; set; }
        public Nullable<int> Point_Sun { get; set; }
        public Nullable<int> Exclusion1_ID { get; set; }
        public Nullable<int> Exclusion2_ID { get; set; }
        public Nullable<int> Exclusion3_ID { get; set; }
        public Nullable<int> Exclusion4_ID { get; set; }
        public Nullable<int> Exclusion5_ID { get; set; }
        public Nullable<int> Parent_Org_ID { get; set; }
        public Nullable<int> Parent_Container_ID { get; set; }
        public Nullable<int> Rule_Type_ID { get; set; }
        public Nullable<int> Rule_Unification { get; set; }
        public Nullable<int> Point_ID { get; set; }
        public Nullable<int> Point2_ID { get; set; }
        public Nullable<int> Object_ID { get; set; }
        public Nullable<double> Max_Range { get; set; }
        public Nullable<double> Remaning_Range { get; set; }
        public Nullable<double> Max_Time { get; set; }
        public Nullable<double> Remaining_Time { get; set; }
        public Nullable<double> Start_Time_Offset { get; set; }
        public Nullable<double> End_Time_Margin { get; set; }
        public Nullable<double> BreakDuration { get; set; }
        public Nullable<double> BreakShiftMins { get; set; }
        public Nullable<double> Break_TW_Mins { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<double> Min_Stops { get; set; }
        public Nullable<double> Max_Stops { get; set; }
        public Nullable<double> Min_Value { get; set; }
        public Nullable<double> Max_Value { get; set; }
        public Nullable<double> Max_Cycle { get; set; }
        public string XIXO { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Containers Containers { get; set; }
    }
}
