//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTConfig
    {
        public int CTC_ID { get; set; }
        public int Container_ID { get; set; }
        public Nullable<int> Task_Type_ID { get; set; }
        public string Container_Description { get; set; }
        public string Container_Address { get; set; }
        public string Container_Address_Coordinates { get; set; }
        public string Container_Language { get; set; }
        public Nullable<bool> Container_Interested { get; set; }
        public Nullable<bool> Container_Active { get; set; }
        public Nullable<int> Terminal_ID { get; set; }
        public Nullable<int> Container_Parent_ID { get; set; }
        public string License_Code { get; set; }
        public Nullable<int> Start_Point_ID { get; set; }
        public Nullable<int> End_Point_ID { get; set; }
        public Nullable<int> Sub_Route_ID { get; set; }
        public Nullable<int> SpcfPoint_ID { get; set; }
        public Nullable<int> SpcfPoint2ID { get; set; }
        public Nullable<int> Max_Range { get; set; }
        public Nullable<int> Remaning_Range { get; set; }
        public Nullable<int> Max_Time { get; set; }
        public Nullable<int> Remaining_Time { get; set; }
        public Nullable<int> Start_Time_Offset { get; set; }
        public Nullable<int> End_Time_Margin { get; set; }
        public Nullable<System.DateTime> Schd_Start_Time { get; set; }
        public Nullable<System.DateTime> Schd_End_Time { get; set; }
        public Nullable<int> BreakDuration { get; set; }
        public Nullable<int> BreakShiftMins { get; set; }
        public Nullable<int> Break_TW_Mins { get; set; }
    }
}
