//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Periods_Files
    {
        public int Object_Periods_File_ID { get; set; }
        public Nullable<int> Point_Periods_ID { get; set; }
        public Nullable<int> Object_Period_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string ActualFileName { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string MimeType { get; set; }
    }
}
