//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Vector
    {
        public int Obj_Vector_ID { get; set; }
        public Nullable<int> Session_ID { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<int> Object_ID { get; set; }
        public Nullable<int> Point_Periods_ID { get; set; }
        public Nullable<int> Point_ID { get; set; }
        public Nullable<int> Action_ID { get; set; }
        public Nullable<System.DateTime> Object_Time { get; set; }
        public string Point_Coordinates { get; set; }
        public Nullable<decimal> Expected_Duration { get; set; }
        public Nullable<System.DateTime> Action_Time { get; set; }
        public string Action_Location { get; set; }
        public Nullable<System.DateTime> Complete_Time { get; set; }
        public string Complete_Location { get; set; }
        public Nullable<int> Action_Time_OK { get; set; }
        public Nullable<int> Action_Loc_OK { get; set; }
        public Nullable<int> Action_OK { get; set; }
        public Nullable<decimal> Action_Score { get; set; }
        public Nullable<decimal> Action_Conf { get; set; }
        public Nullable<int> Preferred_Order { get; set; }
        public Nullable<decimal> T { get; set; }
        public Nullable<decimal> D { get; set; }
        public int SetID { get; set; }
        public Nullable<int> Live { get; set; }
        public string Time_Span { get; set; }
        public Nullable<decimal> Location_Span { get; set; }
        public Nullable<int> Container_ID { get; set; }
        public Nullable<int> Object_Periods_ID { get; set; }
        public string Skills_List { get; set; }
    }
}
