//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Periods
    {
        public int iObjPeriodID { get; set; }
        public int Route_ID { get; set; }
        public int Point_ID { get; set; }
        public int Object_ID { get; set; }
        public Nullable<int> Object_Action_ID { get; set; }
        public Nullable<int> ObjectType_ID { get; set; }
        public Nullable<int> Hierarchy { get; set; }
        public Nullable<int> Container_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> PPR_ID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public bool Sun { get; set; }
        public bool Mon { get; set; }
        public bool Tue { get; set; }
        public bool Wed { get; set; }
        public bool Thu { get; set; }
        public bool Fri { get; set; }
        public bool Sat { get; set; }
        public Nullable<int> Object_Play { get; set; }
        public Nullable<int> Point_Play { get; set; }
        public Nullable<int> Action_Play { get; set; }
        public string Play_Seq { get; set; }
        public Nullable<int> Demand { get; set; }
        public Nullable<int> Demand2 { get; set; }
        public string Demands_List { get; set; }
        public string Types_List { get; set; }
        public Nullable<int> Penalty { get; set; }
        public Nullable<int> Box_ID { get; set; }
        public Nullable<int> Compartment_ID { get; set; }
        public string Comp_Code { get; set; }
        public Nullable<int> Object_RF_ID { get; set; }
        public Nullable<int> OPR_ID { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> Action_Order { get; set; }
        public Nullable<decimal> Max_Speed { get; set; }
        public Nullable<int> ParentOPR_ID { get; set; }
        public Nullable<int> RelTypeIndex { get; set; }
        public Nullable<decimal> PreDistance { get; set; }
        public Nullable<decimal> PostDistance { get; set; }
        public Nullable<decimal> PreTime { get; set; }
        public Nullable<decimal> PostTime { get; set; }
        public Nullable<int> ChannelGroup { get; set; }
        public Nullable<int> ParentActionID { get; set; }
        public Nullable<bool> IncludeParent { get; set; }
        public Nullable<bool> Include { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> State { get; set; }
        public string RelatedObjects { get; set; }
        public Nullable<decimal> Offset { get; set; }
        public Nullable<int> Object_ID2 { get; set; }
        public Nullable<bool> Specific { get; set; }
        public Nullable<int> Expedite_Factor { get; set; }
        public Nullable<int> Pref_Container { get; set; }
        public Nullable<int> Pref_Value { get; set; }
        public Nullable<int> Pref_Group { get; set; }
        public Nullable<System.DateTime> Object_Time { get; set; }
        public Nullable<int> Action_Time_OK { get; set; }
        public Nullable<int> Action_Loc_OK { get; set; }
        public Nullable<int> Action_OK { get; set; }
        public Nullable<decimal> T { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<int> Live { get; set; }
        public string Object { get; set; }
        public Nullable<System.DateTime> Action_Time { get; set; }
        public string Action_Location { get; set; }
        public string Aggr_List { get; set; }
        public string Non_List { get; set; }
        public Nullable<int> Units { get; set; }
    
        public virtual Actions_Type Actions_Type { get; set; }
        public virtual Object Objects { get; set; }
        public virtual Point Points { get; set; }
        public virtual Route Routes { get; set; }
    }
}
