//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Types
    {
        public int Object_Type_ID { get; set; }
        public string Object_Type_Name { get; set; }
        public string Object_Type_Order { get; set; }
        public string Object_Type_Icon { get; set; }
    }
}
