//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public int Period_ID { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<int> Point_Mon { get; set; }
        public Nullable<int> Point_Tue { get; set; }
        public Nullable<int> Point_Wed { get; set; }
        public Nullable<int> Point_Thu { get; set; }
        public Nullable<int> Point_Fri { get; set; }
        public Nullable<int> Point_Sat { get; set; }
        public Nullable<int> Point_Sun { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Time_Mon { get; set; }
        public string Time_Tue { get; set; }
        public string Time_Wed { get; set; }
        public string Time_Thu { get; set; }
        public string Time_Fri { get; set; }
        public string Time_Sat { get; set; }
        public string Time_Sun { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
    
        public virtual Period Period1 { get; set; }
        public virtual Period Period2 { get; set; }
        public virtual Point Point { get; set; }
        public virtual Point Point1 { get; set; }
        public virtual Point Point2 { get; set; }
        public virtual Point Point3 { get; set; }
        public virtual Point Point4 { get; set; }
        public virtual Point Point5 { get; set; }
    }
}
