//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public Point()
        {
            this.Periods = new HashSet<Period>();
            this.Periods1 = new HashSet<Period>();
            this.Periods2 = new HashSet<Period>();
            this.Periods3 = new HashSet<Period>();
            this.Periods4 = new HashSet<Period>();
            this.Periods5 = new HashSet<Period>();
            this.Point_Periods = new HashSet<Point_Periods>();
            this.Object_Periods = new HashSet<Object_Periods>();
        }
    
        public int Point_ID { get; set; }
        public Nullable<int> Point_Type_ID { get; set; }
        public Nullable<int> Point_Number { get; set; }
        public Nullable<int> Preferred_Order { get; set; }
        public string Point_Name { get; set; }
        public string User_Message { get; set; }
        public string Notification { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Point_Coordinates { get; set; }
        public Nullable<decimal> Point_Orientation { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<System.DateTime> Interval { get; set; }
        public Nullable<double> Monetary { get; set; }
        public Nullable<int> Load_OK { get; set; }
        public Nullable<System.DateTime> Load_Time { get; set; }
        public Nullable<int> Offload_OK { get; set; }
        public Nullable<System.DateTime> Offload_Time { get; set; }
        public string Point_Pic { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> Load_OffloadN { get; set; }
        public Nullable<int> Action_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Action_Type_ID { get; set; }
        public Nullable<System.DateTime> sStandardTime { get; set; }
        public string sLatitude { get; set; }
        public string sLongitude { get; set; }
        public string sDragPoints { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<bool> btIsMapRoute { get; set; }
        public string Point_Snd { get; set; }
        public Nullable<decimal> MaxSpeed { get; set; }
        public Nullable<int> PickEntryDuration { get; set; }
        public Nullable<int> PickExitDuration { get; set; }
        public Nullable<int> DropEntryDuration { get; set; }
        public Nullable<int> DropExitDuration { get; set; }
        public Nullable<int> OpenMins { get; set; }
        public Nullable<int> CloseMins { get; set; }
        public string TypesList { get; set; }
        public string NonList { get; set; }
        public Nullable<int> Concurrent { get; set; }
        public string Point_Address { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public string SStd { get; set; }
        public string SMon { get; set; }
        public string STue { get; set; }
        public string SWed { get; set; }
        public string SThu { get; set; }
        public string SFri { get; set; }
        public string SSat { get; set; }
        public string SSun { get; set; }
        public string FStd { get; set; }
        public string FMon { get; set; }
        public string FTue { get; set; }
        public string FWed { get; set; }
        public string FThu { get; set; }
        public string FFri { get; set; }
        public string FSat { get; set; }
        public string FSun { get; set; }
        public Nullable<bool> AllMon { get; set; }
        public Nullable<bool> AllTue { get; set; }
        public Nullable<bool> AllWed { get; set; }
        public Nullable<bool> AllThu { get; set; }
        public Nullable<bool> AllFri { get; set; }
        public Nullable<bool> AllSat { get; set; }
        public Nullable<bool> AllSun { get; set; }
    
        public virtual ICollection<Period> Periods { get; set; }
        public virtual ICollection<Period> Periods1 { get; set; }
        public virtual ICollection<Period> Periods2 { get; set; }
        public virtual ICollection<Period> Periods3 { get; set; }
        public virtual ICollection<Period> Periods4 { get; set; }
        public virtual ICollection<Period> Periods5 { get; set; }
        public virtual ICollection<Point_Periods> Point_Periods { get; set; }
        public virtual ICollection<Object_Periods> Object_Periods { get; set; }
    }
}
