//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteType
    {
        public RouteType()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int Route_Type_ID { get; set; }
        public string Route_Type_Name { get; set; }
    
        public virtual ICollection<Route> Routes { get; set; }
    }
}
