//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Container_Periods = new HashSet<Container_Periods>();
            this.Point_Periods = new HashSet<Point_Periods>();
            this.User_Periods = new HashSet<User_Periods>();
            this.Object_Periods = new HashSet<Object_Periods>();
        }
    
        public int Route_ID { get; set; }
        public Nullable<int> Route_Number { get; set; }
        public string Route_Name { get; set; }
        public Nullable<int> Route_Type_ID { get; set; }
        public Nullable<int> Route_Action_ID { get; set; }
        public Nullable<System.DateTime> Route_Start_Time { get; set; }
        public Nullable<int> Route_Controller1_ID { get; set; }
        public Nullable<int> Route_Controller1_Type { get; set; }
        public Nullable<int> Route_Controller2_ID { get; set; }
        public Nullable<int> Route_Controller2_Type { get; set; }
        public Nullable<int> Route_Controller3_ID { get; set; }
        public Nullable<int> Route_Controller3_Type { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public Nullable<int> Route_Carrier_ID { get; set; }
        public System.DateTime Activation_Date { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public Nullable<System.DateTime> Forced_Expiry_Date { get; set; }
        public string Coordinates { get; set; }
        public Nullable<int> Total_Distance { get; set; }
        public Nullable<int> Total_Interval { get; set; }
        public double Monetary { get; set; }
        public System.DateTime Route_Start_Date { get; set; }
        public Nullable<System.DateTime> Route_End_Date { get; set; }
        public string Message { get; set; }
        public Nullable<int> Max_Allowed { get; set; }
        public Nullable<int> Point_ID { get; set; }
        public string Start_Point { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Original_Route_ID { get; set; }
        public Nullable<int> Hierarchy { get; set; }
        public Nullable<int> Sub_Route_ID { get; set; }
        public Nullable<int> mode_in_profile { get; set; }
        public Nullable<System.DateTime> ActivityStartDate { get; set; }
        public Nullable<System.DateTime> ActivityEndDate { get; set; }
        public Nullable<double> minlat { get; set; }
        public Nullable<double> minlng { get; set; }
        public Nullable<double> Span { get; set; }
        public Nullable<int> Time_Span { get; set; }
        public Nullable<int> Location_Span { get; set; }
    
        public virtual ICollection<Container_Periods> Container_Periods { get; set; }
        public virtual ICollection<Point_Periods> Point_Periods { get; set; }
        public virtual RouteType RouteType { get; set; }
        public virtual ICollection<User_Periods> User_Periods { get; set; }
        public virtual ICollection<Object_Periods> Object_Periods { get; set; }
    }
}
