//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegmentTracking
    {
        public decimal Tracker_ID { get; set; }
        public Nullable<int> Segment_K { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<int> Session_ID { get; set; }
        public Nullable<bool> MonitorState { get; set; }
        public string DEndSeg0 { get; set; }
        public string DMIN { get; set; }
        public string DENDSEG { get; set; }
        public string DIN { get; set; }
        public string DREQ { get; set; }
        public string HYST { get; set; }
        public Nullable<bool> IsAlert { get; set; }
    }
}
