//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceApp.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Periods
    {
        public int User_Period_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Route_ID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thu { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<int> Point_Mon { get; set; }
        public Nullable<int> Point_Tue { get; set; }
        public Nullable<int> Point_Wed { get; set; }
        public Nullable<int> Point_Thu { get; set; }
        public Nullable<int> Point_Fri { get; set; }
        public Nullable<int> Point_Sat { get; set; }
        public Nullable<int> Point_Sun { get; set; }
        public Nullable<int> Exclusion1_ID { get; set; }
        public Nullable<int> Exclusion2_ID { get; set; }
        public Nullable<int> Exclusion3_ID { get; set; }
        public Nullable<int> Exclusion4_ID { get; set; }
        public Nullable<int> Exclusion5_ID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string SMon { get; set; }
        public string STue { get; set; }
        public string SWed { get; set; }
        public string SThu { get; set; }
        public string SFri { get; set; }
        public string SSat { get; set; }
        public string SSun { get; set; }
        public string FMon { get; set; }
        public string FTue { get; set; }
        public string FWed { get; set; }
        public string FThu { get; set; }
        public string FFri { get; set; }
        public string FSat { get; set; }
        public string FSun { get; set; }
        public Nullable<bool> AllMon { get; set; }
        public Nullable<bool> AllTue { get; set; }
        public Nullable<bool> AllWed { get; set; }
        public Nullable<bool> AllThu { get; set; }
        public Nullable<bool> AllFri { get; set; }
        public Nullable<bool> AllSat { get; set; }
        public Nullable<bool> AllSun { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
